### ISSUE TITLE
Crash while looking at SK inventory

### ISSUE THREAD

**Issue by w1r3dh4ck3r** [paradoxReborn/SurvivalReborn-Spacewalk#1] opened 2022-08-07 14:50 UTC
`2022-08-07 11:46:32.230 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at SurvivalReborn.SRSpacewalk.SRCharacterInfo..ctor(IMyCharacter character)
   at SurvivalReborn.SRSpacewalk.MyEntities_OnEntityAdd(MyEntity obj)
   at System.Action`1.Invoke(T obj)
   at Sandbox.Game.Entities.MyEntities.RaiseEntityAdd(MyEntity entity)
   at Sandbox.Game.Entities.MyEntities.Add(MyEntity entity, Boolean insertIntoScene)
   at Sandbox.Game.Entities.Character.MyCharacter.CreateCharacterBase(MatrixD worldMatrix, Vector3& velocity, String characterName, String model, Nullable`1 colorMask, Boolean AIMode, Boolean useInventory, MyBotDefinition botDefinition, Int64 identityId, Boolean addDefaultItems)
   at Sandbox.Game.Entities.Character.MyCharacter.CreateCharacter(MatrixD worldMatrix, Vector3 velocity, String characterName, String model, Nullable`1 colorMask, MyBotDefinition botDefinition, Boolean findNearPos, Boolean AIMode, MyCockpit cockpit, Boolean useInventory, Int64 identityId, Boolean addDefaultItems)
   at Sandbox.Game.World.MyPlayer.SpawnAt(MatrixD worldMatrix, Vector3 velocity, MyEntity spawnedBy, MyBotDefinition botDefinition, Boolean findFreePlace, String modelName, Nullable`1 color)
   at SpaceEngineers.Game.World.MySpaceRespawnComponent.HandleRespawnRequest(Boolean joinGame, Boolean newIdentity, Int64 respawnEntityId, String respawnShipId, PlayerId playerId, Nullable`1 spawnPosition, Nullable`1 direction, Nullable`1 up, Nullable`1 botDefinitionId, Boolean realPlayer, String modelName, Color color)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.OnRespawnRequest(Boolean joinGame, Boolean newIdentity, Int64 respawnEntityId, String respawnShipId, Nullable`1 spawnPosition, Nullable`1 direction, Nullable`1 up, Nullable`1 botDefinitionId, Boolean realPlayer, Int32 playerSerialId, String modelName, Color color)
   at Sandbox.Game.AI.MyAgentBot.Spawn(Nullable`1 spawnPosition, Nullable`1 direction, Nullable`1 up, Boolean spawnedByPlayer)
   at Sandbox.Game.AI.MyAIComponent.CreateBot(Int32 playerNumber, MyObjectBuilder_Bot botBuilder)
   at Sandbox.Game.AI.MyAIComponent.PlayerCreated(PlayerId playerId)
   at System.Action`1.Invoke(T obj)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.OnNewPlayerSuccess(UInt64 clientSteamId, Int32 playerSerialId)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.OnNewPlayerRequest(NewPlayerRequestParameters parameters)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.OnNewPlayerRequest<>Sandbox_Game_Multiplayer_MyPlayerCollection<>NewPlayerRequestParameters.Invoke(IMyEventOwner& <static>, NewPlayerRequestParameters& parameters, DBNull& arg2, DBNull& arg3, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationSingle.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3](T1 arg1, T3 arg3, Func`2 action, T2 arg2, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.RequestNewPlayer(UInt64 steamId, Int32 serialNumber, String playerName, String characterModel, Boolean realPlayer, Boolean initialPlayer, Boolean isWildlifeAgent)
   at Sandbox.Game.AI.MyAIComponent.SpawnAgent(AgentSpawnData& newBotData)
   at Sandbox.Game.AI.MyAIComponent.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2022-08-07 11:46:32.230 - Thread:   1 ->  Showing message
2022-08-07 11:46:33.123 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_201_013
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 292
PCUCount: 23179
IsHang: False
GCMemory: 1745
GCMemoryAllocated: 1745
HWAvailableMemory: 4224
ProcessPrivateMemory: 7346
AnalyticId: SE
================================== OFNI HSARC ==================================

2022-08-07 11:46:33.123 - Thread:   1 ->  Log Closed`

**Comment by paradoxReborn** [comment] 2022-08-08 02:19
I'm not able to reproduce this bug, so I need additional information to determine the exact cause. The next version will include more logging to try to pin this down.

For now, please provide the rest of the log at least beginning with the message "SurvivalReborn: Loaded Spacewalk Beta 0.5." The stacktrace alone isn't enough.

**Comment by paradoxReborn** [comment] 2022-08-08 02:53
Did this happen on singleplayer or multiplayer? What were you doing besides looking at a survival kit inventory? Were you in space? on the ground? Was your jetpack on? Did you have any hydrogen bottles in your inventory? Were you moving items in or out of your inventory?

**Comment by w1r3dh4ck3r** [comment] 2022-08-08 03:12
I was just watching things craft, no bottles in inventory but in the rover
there where one oxy and one hydro I was not even looking at them, I was
besides my rover in the ground literally just standing there with the menu
on the survival kit open, crash happened twice after I added the mod to my
mod list thought it could be some incompatible mods but haven't tested it
in a clean save yet, I was using Survival Less Likely mod that has some
features that might be incompatible with this so there is that.

**Comment by paradoxReborn** [comment] 2022-08-08 03:20
That's almost certainly a mod conflict. My next version will include more logging to try to track it down.

**Comment by w1r3dh4ck3r** [comment] 2022-08-08 03:22
Ok, I said I did not test it but I kinda did just the load order it did not
matter it just crashed the same way, tomorrow I'll test it with a clean
save most likely won't happen.

**Comment by paradoxReborn** [comment] 2022-08-08 04:36
I've released a new version with additional checks and logging to try to catch what's happening. Please try again with all of your mods to see if you get an error message. If so, attach your full log here. It may save time if you can determine which mod is causing the issue.

**Comment by paradoxReborn** [comment] 2022-08-13 14:51
I've downloaded Survival Less Likely. It does not appear to do anything that might cause a mod conflict. (It has no scripts, only SBC changes.) Were you using any other mods when this crash occurred?

**Comment by paradoxReborn** [comment] 2022-08-23 00:11
I'm closing this as it doesn't seem possible to reproduce with the information provided. It's likely related to issue #3, in which case it's probably fixed anyway.

**Closed as not planned by paradoxReborn** 2022-08-23 00:11 UTC
